#frontend:
#  javascript_version: auto
#  extra_html_url:
#    - /local/custom_ui/more-info-qinver-tv.html
#  extra_html_url_es5:
#    - /local/custom_ui/more-info-qinver-tv.html
###以上是将custom_ui的文件加入到HA中的格式!请在对应位置添加！！
    
input_boolean:
  boolean_tvceshi1:
  boolean_tvceshi2:
  boolean_tvceshi3:
  boolean_tvceshi4:

##上面这部分仅仅用于举例测试用。没有实际功能。
    
#下面是一个完整的配置写法
homeassistant:
  customize:
    input_boolean.boolean_tvceshi2:
      friendly_name: 测试遥控器2
      icon: mdi:television-guide
      custom_ui_more_info: more-info-qinver-tv   ##使用此自定义详情页面
      entities:               #以下是触控滑动功能的ID
        menu: script.bl_cmcc_hezi_menu
        home: script.bl_cmcc_hezi_home
        back: script.bl_cmcc_hezi_back
        up: script.bl_cmcc_hezi_shang
        down: script.bl_cmcc_hezi_xia
        left: script.bl_cmcc_hezi_zuo
        right: script.bl_cmcc_hezi_you
        ok: script.bl_cmcc_hezi_ok
        buttons:             #除了触控区，你还需要增加的按钮
          - entity: input_boolean.boolean_tvceshi1
            icon: mdi:skip-previous-circle-outline   #icon可以如果不填则为默认图标
          - entity: input_boolean.boolean_tvceshi2
          - entity: input_boolean.boolean_tvceshi3
            icon: mdi:format-list-bulleted
          - entity: input_boolean.boolean_tvceshi4
            icon: mdi:backup-restore
            
            
#这个项目是自定义详情页，也就是点击卡片弹出来的页面，那么它可以与其他任何自定义卡片UI一起使用！
#以下是一个与我之前制作的state-card-button（自定义按钮卡片）一起使用的例子：
#state-card-button（自定义按钮卡片）项目地址：https://github.com/Qinver-china/homeassistant-Custom_UI.state-card-button
    input_boolean.boolean_tvceshi1:
      friendly_name: 测试遥控器1
      icon: mdi:television-guide
      custom_ui_state_card: state-card-button    #这里使用自定义卡片UI，也可以使用其他的
      config:
        gap: 10px                   # 间距（默认为8px）
        ha_entity_toggle_display: none    # 不显示右边本来的按钮（默认显示）
        entities:
          - entity: script.bl_cmcc_hezi_home               #这是我的home按钮
            icon: mdi:home-outline                       
          - entity: script.bl_cmcc_hezi_voljian            #音量-
            icon: mdi:volume-minus
          - entity: script.bl_cmcc_hezi_voljia             #音量+ 
            icon: mdi:volume-plus
          - entity: script.bl_cmcc_hezi_kaiguan            #电源开关按钮
            icon: mdi:power
            color_off: '#E45E65'                           #电源按钮我把他设为红色
##上面配置为自定义按钮 卡片ui，详情请看项目
##下面开始自定义详情页遥控器UI配置，同示例一
      custom_ui_more_info: more-info-qinver-tv   ##使用此自定义详情页面
      entities:               #以下是触控滑动功能的ID
        menu: script.bl_cmcc_hezi_menu
        home: script.bl_cmcc_hezi_home
        back: script.bl_cmcc_hezi_back
        up: script.bl_cmcc_hezi_shang
        down: script.bl_cmcc_hezi_xia
        left: script.bl_cmcc_hezi_zuo
        right: script.bl_cmcc_hezi_you
        ok: script.bl_cmcc_hezi_ok
        buttons:             #除了触控区，你还需要增加的按钮
          - entity: input_boolean.boolean_tvceshi1
            icon: mdi:skip-previous-circle-outline  #icon可以如果不填则为默认图标
          - entity: input_boolean.boolean_tvceshi2
          - entity: input_boolean.boolean_tvceshi3
            icon: mdi:format-list-bulleted
          - entity: input_boolean.boolean_tvceshi4
            icon: mdi:backup-restore
###用于media_player组件的例子!
    media_player.kodi:
      custom_ui_more_info: more-info-qinver-tv   ##使用此自定义详情页面
      media_player_display: yes     #显示media_player的原按钮,仅适用于media_player组件.默认为no,不显示
      entities:               #以下是触控滑动功能的ID
        menu: script.bl_cmcc_hezi_menu
        home: script.bl_cmcc_hezi_home
        back: script.bl_cmcc_hezi_back
        up: script.bl_cmcc_hezi_shang
        down: script.bl_cmcc_hezi_xia
        left: script.bl_cmcc_hezi_zuo
        right: script.bl_cmcc_hezi_you
        ok: script.bl_cmcc_hezi_ok
